### ISSUE TITLE
Fails to install with inspec 4.6.4 on CentOS 6

### ISSUE THREAD

**Issue by jamdev12** [alexpop/inspec-reporter-pophtml#1]
Git cloned your repo as per instructions.

Then ran inspec plugin install inspec-reporter-pophtml, but get the following errors:

    Traceback (most recent call last):
	    20: from /usr/bin/inspec:155:in `<main>'
	    19: from /usr/bin/inspec:155:in `load'
	    18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.6.4/bin/inspec:11:in `<top (required)>'
	    17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	    16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	    15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	    14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	    13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	    12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	    11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	    10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	     9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	     8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:98:in `install'
	     7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:215:in `install_from_path'
	     6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:289:in `install_from_path__probe_load'
	     5: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	     4: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	     3: from /home/user/inspec_reports/inspec-reporter-pophtml/lib/inspec-reporter-pophtml.rb:5:in `<top (required)>'
	     2: from /home/user/inspec_reports/inspec-reporter-pophtml/lib/inspec-reporter-pophtml.rb:6:in `<module:InspecPlugins>'
	     1: from /home/user/inspec_reports/inspec-reporter-pophtml/lib/inspec-reporter-pophtml.rb:7:in `<module:PopHtmlReporter>'
    /home/user/inspec_reports/inspec-reporter-pophtml/lib/inspec-reporter-pophtml.rb:12:in `<class:Plugin>': undefined method `reporter' for InspecPlugins::PopHtmlReporter::Plugin:Class (NoMethodError)

Running this on CentOS 6 with Inspec version 4.6.4.

**Comment by alexpop** [comment]
Hey @jamdev12 thank you for the ticket and sorry for not seeing this issue until now. Did you manage to get past the error?

I have this plugin running fine with InSpec version 4.22.22 in a pipeline.

**Comment by alexpop** [comment]
Tried it again with latest InSpec / cinc-auditor `v4.52.9` and it's installing fine. Please reopen if still facing the error on newer version of InSpec. Thank you.
