### ISSUE TITLE
Error wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by edgard** [alexpop/inspec-reporter-pophtml#2]
Running last git source or releases 0.6/0.7 gives the same error:"

"wrong number of arguments (given 0, expected 1)"

The switch i'm using is "--reporter pophtml:./test.html"

Any idea what that could be?

**Comment by Aniket281292** [comment]
@edgard i am facing the same issue. were you able to resolve this error by any chance?

**Comment by alexpop** [comment]
Hey, I run it like this without problems:
```bash
inspec exec ~/git/myprofile --reporter pophtml:/tmp/pophtml.html
```

**Comment by framegrace** [comment]
Same here... 

$ inspec exec atestprofile/ --input-file attributes.yml --reporter pophtml:./report.html
wrong number of arguments (given 0, expected 1)

**Comment by TheSpartan1980** [comment]
Did anyone manage to find out what the issue was? I'm still encountering this issue I am using inspec version `4.46.13`

**Comment by alexpop** [comment]
I'll have a look into this, will reply later.

**Comment by alexpop** [comment]
I reproduced the issues with cinc-auditor `v4.52.9` and opened a pull request for a fix. Please confirm if it fixes the error on your end as well. Cheers!

**Comment by edgard** [comment]
That indeed fixed for me, thanks!!

**Comment by alexpop** [comment]
Thank you @edgard for confirming, I'll merge and close the ticket.
